#!/bin/bash
echo "🛒 CARRITO DE COMPRAS - GUÍA DE INICIO RÁPIDO"
echo "=============================================="
echo ""
echo "✅ PASO 1: BASE DE DATOS (Si aún no está hecha)"
echo "   - Abrir DBeaver"
echo "   - Click derecho en 'carrito_db'"
echo "   - SQL Editor → Open SQL Script"
echo "   - Seleccionar 'init-db.sql'"
echo "   - Ctrl+A → Ctrl+Enter"
echo ""
echo "✅ PASO 2: INSTALAR DEPENDENCIAS"
cd backend
npm install
echo ""
echo "✅ PASO 3: VARIABLES DE ENTORNO"
echo "   - Crear archivo: backend/.env"
echo "   - Copiar de: backend/.env.example"
echo ""
echo "✅ PASO 4: INICIAR SERVIDOR"
echo "   Ejecutar:"
echo "   npm run dev"
echo ""
echo "✅ PASO 5: ABRIR EN NAVEGADOR"
echo "   http://localhost:3000"
echo ""
echo "👤 CUENTAS DEMO:"
echo "   Admin: admin@example.com / pass"
echo "   Vendedor: vendor@example.com / pass"
echo "   Cliente: user1@example.com / pass"
echo ""
echo "🚀 ¡LISTO!"
